create database crud_php;

CREATE TABLE `vendedores` (
	`ID` INT(20) NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(100) NOT NULL DEFAULT '0' COLLATE 'utf8_unicode_ci',
	`EMAIL` VARCHAR(100) NOT NULL DEFAULT '0' COLLATE 'utf8_unicode_ci',
	`COMISSAO` DOUBLE(10,2) NOT NULL DEFAULT '8.50',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=19
;
